// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:235810189345:web:17c2285df1fa4135793360',
    messagingSenderId: '235810189345',
    projectId: 'attendance-app-491f1',
    authDomain: 'attendance-app-491f1.firebaseapp.com',
    storageBucket: 'attendance-app-491f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:235810189345:android:39becb39fb74d90c793360',
    messagingSenderId: '235810189345',
    projectId: 'attendance-app-491f1',
    storageBucket: 'attendance-app-491f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:235810189345:ios:8b06228ab33f5dd9793360',
    messagingSenderId: '235810189345',
    projectId: 'attendance-app-491f1',
    storageBucket: 'attendance-app-491f1.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkKFhUWsPMyGm9f-exluBHUrmYI0Q_syQ',
    appId: '1:235810189345:ios:8b06228ab33f5dd9793360',
    messagingSenderId: '235810189345',
    projectId: 'attendance-app-491f1',
    storageBucket: 'attendance-app-491f1.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3go3bAsd1ZBirVquiXMLHhGZxWoPbdKM',
    appId: '1:235810189345:web:5630f465a3bbcd2c793360',
    messagingSenderId: '235810189345',
    projectId: 'attendance-app-491f1',
    authDomain: 'attendance-app-491f1.firebaseapp.com',
    storageBucket: 'attendance-app-491f1.firebasestorage.app',
  );
}
